version: '3.8'
services:
  db:
    image: ankane/pgvector:postgres-15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Parth@123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
